
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 48;
  public static final int GE = 7;
  public static final int DOUBLE = 28;
  public static final int PRIVATE = 53;
  public static final int CONTINUE = 43;
  public static final int LPAREN = 20;
  public static final int INTERFACE = 32;
  public static final int INT = 27;
  public static final int FOR = 37;
  public static final int MINUS = 11;
  public static final int RPAREN = 21;
  public static final int NOT = 18;
  public static final int SEMICOLON = 19;
  public static final int AND = 9;
  public static final int READINTEGER = 47;
  public static final int LT = 5;
  public static final int OR = 10;
  public static final int BOOL = 29;
  public static final int COMMA = 17;
  public static final int CLASS = 31;
  public static final int DIV = 12;
  public static final int NEWARRAY = 45;
  public static final int PLUS = 14;
  public static final int IF = 39;
  public static final int ASSIGN = 8;
  public static final int THIS = 34;
  public static final int DOT = 16;
  public static final int LE = 4;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int DOUBLELITERAL = 58;
  public static final int TRUE = 60;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int LCURLY = 24;
  public static final int NULL = 33;
  public static final int MOD = 13;
  public static final int IDENT = 56;
  public static final int BREAK = 42;
  public static final int VOID = 26;
  public static final int EQ = 2;
  public static final int DTOI = 49;
  public static final int LBRACK = 22;
  public static final int RCURLY = 25;
  public static final int INTLITERAL = 57;
  public static final int ELSE = 40;
  public static final int PROTECTED = 54;
  public static final int ITOD = 50;
  public static final int RBRACK = 23;
  public static final int ITOB = 52;
  public static final int WHILE = 38;
  public static final int PUBLIC = 55;
  public static final int BTOI = 51;
  public static final int EXTENDS = 35;
  public static final int NE = 3;
  public static final int PROD = 15;
  public static final int STRING = 30;
  public static final int STRINGLITERAL = 59;
  public static final int FALSE = 61;
  public static final int IMPLEMENTS = 36;
  public static final int GT = 6;
  public static final int PRINT = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQ",
  "NE",
  "LE",
  "LT",
  "GT",
  "GE",
  "ASSIGN",
  "AND",
  "OR",
  "MINUS",
  "DIV",
  "MOD",
  "PLUS",
  "PROD",
  "DOT",
  "COMMA",
  "NOT",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LCURLY",
  "RCURLY",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "INTERFACE",
  "NULL",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "NEW",
  "NEWARRAY",
  "PRINT",
  "READINTEGER",
  "READLINE",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "IDENT",
  "INTLITERAL",
  "DOUBLELITERAL",
  "STRINGLITERAL",
  "TRUE",
  "FALSE"
  };
}

